# Generated by Django 4.0.4 on 2022-05-10 19:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('DOB', models.DateField()),
                ('age', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player_category', models.CharField(choices=[('Age_Group', 'Age_Group'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Captain', 'Captain')], default='Junior', max_length=10)),
            ],
        ),
    ]
