# Generated by Django 4.0.4 on 2022-05-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_created_at_player_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='modified_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
